### ISSUE TITLE
How to fix the "generate animation" gitflow action issue

### ISSUE THREAD

**Issue by jonathanlbt1** [wolwerr/wolwerr#2]
Olá Ricardo! 
Para corrigir o problema do "generate animation" no gitactions do seu README só abrir o arquivo main.yml na pasta .github/workflows e atualizar a versao de v2 para v3 do Platane/snk/svg-only@v3. Fica assim o resultado:

`jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:`

**Comment by wolwerr** [comment]
Deu certo!!

Muito obrigado
